version: '3.7'
services:
  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  vector-db:
    image: qdrant/qdrant:v1.9.2
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
  qbot:
    image: lijingyu68/gt-qbot:dev
    env_file:
      - .env
    environment:
      - G_REDIS_URL=redis://redis:6379
      - QDRANT_URL=vector-db
