version: '3.7'
services:
  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  vector-db:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage